local addSound = love.audio.newSource
BASE_MODULE.Sounds = {}

BASE_MODULE.Sounds["energySound"] = {
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),
    addSound("sound/power1.ogg","static"),
    addSound("sound/power4.wav", "static"),

}
BASE_MODULE.Sounds["damageTake"] = {
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
    addSound("sound/hdmgi.wav","static"),
    addSound("sound/hdmgg.wav","static"),
    addSound("sound/hdmgr.wav","static"),
}
BASE_MODULE.Sounds["damageHard"] = {
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),   
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
    addSound("sound/hdmg1.wav","static"),
    addSound("sound/hdmg2.wav","static"),
}
BASE_MODULE.Sounds["damageDeal"] = {
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),
    addSound("sound/dealdmg.wav","static"),
    addSound("sound/dealdmg2.wav","static"),


}
BASE_MODULE.Sounds["damageSilencer"] = {
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
    addSound("sound/silencer_1.wav","static"),
    addSound("sound/silencer_2.wav","static"),
    addSound("sound/silencer_3.wav","static"),
}
BASE_MODULE.Sounds["Music"] = {}
BASE_MODULE.Sounds["Music"]["Graveyard"] =  addSound("sound/music/graveyard.ogg","stream")
function PlaySound(variant, number)
    if NOSOUND then return false end
    BASE_MODULE.Sounds[variant][(number or 1)]:setVolume(mVolume or 0.45)
    DoNextFrame(function() BASE_MODULE.Sounds[variant][(number or 1)]:play() end)
    return BASE_MODULE.Sounds[variant][(number or 1)]
end